fullnameOverride: request-headers

image:
  repository: jonpulsifer/request-headers
  tag: latest

env:
  - name: NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name

ingress:
  hosts:
    - host: &host "request-headers.lolwtf.ca"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: *host
      hosts:
        - *host
