apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rosie

images:
  - name: jonpulsifer/does-not-exist
    newName: jonpulsifer/rosie
    newTag: latest

resources:
  - ../../../k8s/base/workload

commonLabels:
  app.kubernetes.io/name: rosie
  app.kubernetes.io/part-of: rosie

patches:
  - path: secret.yaml
