apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &app rosie
namePrefix: rosie-
# images:
#   - name: jonpulsifer/does-not-exist
#     newName: ghcr.io/jonpulsifer/rosie
#     newTag: latest
commonLabels:
  app.kubernetes.io/name: *app
  app.kubernetes.io/part-of: *app
resources:
  - ../../../k8s/workload
patches:
  - path: secret.yaml
