---
apiVersion: custom.sandboxes.x-k8s.io/v1alpha1
kind: Application
metadata:
  name: truffle
  namespace: default
spec:
  image: ghcr.io/jonpulsifer/truffle:latest
  version: "latest"
  command: "bun run src/index.ts"
  hostname: truffle.lolwtf.ca
  port: 3000
  replicas: 1
  certIssuer: letsencrypt-production
  ingress:
    enabled: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  database:
    enabled: true
    instances: 1
    size: "1Gi"
    name: "truffle"
    migration:
      enabled: true
      command: "bun run db:migrate && bun run db:seed"
  networkPolicy:
    enabled: false
