apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nested

images:
  - name: jonpulsifer/does-not-exist
    newName: jonpulsifer/nested
    newTag: latest

namePrefix: nested-

replicas:
  - name: app
    count: 2

resources:
  - ../../../k8s/workload
  - ../../../k8s/gateway

commonLabels:
  app.kubernetes.io/name: nested
  app.kubernetes.io/part-of: nested

patches:
  - path: env.yaml
  - path: gateway.yaml
  - path: http-route.yaml
