apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app nested

namePrefix: nested-

images:
  - name: jonpulsifer/does-not-exist
    newName: jonpulsifer/nested
    newTag: latest

commonLabels:
  app.kubernetes.io/name: *app
  app.kubernetes.io/part-of: *app

resources:
  - ../../../k8s/workload
  - ../../../k8s/gateway

replicas:
  - name: app
    count: 2

patches:
  - path: env.yaml
  - path: gateway.yaml
  - path: http-route.yaml
