fullnameOverride: rosie

image:
  repository: jonpulsifer/rosie
  tag: latest

env:
  - name: NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_LABEL_APP_INSTANCE
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['app.kubernetes.io/instance']

envFrom:
  - secretRef:
      name: rosie

podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
