# docker-compose file that runs postgres and pgadmin for my next applicationversion: '3.8'

services:
  redis:
    image: redis:alpine@sha256:a40e29800d387e3cf9431902e1e7a362e4d819233d68ae39380532c3310091ac
    ports:
      - 6379:6379
  # postgres:
  #   image: postgres:15-alpine@sha256:d00564ed4c14d702b7b4465dad4f4621c2eb985a21758b27d20c673b9fc3ebd4
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: authme
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4:latest@sha256:f1460b121383a5d61c20867ecd42535d4aabb385d32685b0e0845367ab9b86c4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - 5050:80
  #   depends_on:
  #     - postgres

volumes:
  postgres-data:
