apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: &app request-headers

namePrefix: request-headers-

images:
  - name: jonpulsifer/does-not-exist
    newName: jonpulsifer/request-headers
    newTag: latest

replicas:
  - name: app
    count: 2

resources:
  - ../../../k8s/workload
  - ../../../k8s/gateway

commonLabels:
  app.kubernetes.io/name: *app
  app.kubernetes.io/part-of: *app

patches:
  - path: env.yaml
  - path: gateway.yaml
  - path: http-route.yaml
