apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: request-headers

images:
  - name: jonpulsifer/does-not-exist
    newName: jonpulsifer/request-headers
    newTag: latest

resources:
  - ../../../k8s/base

commonLabels:
  app.kubernetes.io/name: request-headers
  app.kubernetes.io/part-of: request-headers

patches:
  - path: env.yaml
  - path: gateway.yaml
  - path: http-route.yaml
