apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app.kubernetes.io/created-by: kustomize
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      containers:
        - name: app
          containerPort: 8080
          image: jonpulsifer/does-not-exist
