apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  gatewayClassName: cilium
  listeners:
    - name: tls-gateway
      protocol: HTTPS
      port: 443
