DROP TABLE IF EXISTS checks CASCADE;
DROP TABLE IF EXISTS deployments CASCADE;
DROP TABLE IF EXISTS projects CASCADE;

CREATE TABLE IF NOT EXISTS specimens (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  species TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'dormant',
  spore_count INTEGER NOT NULL DEFAULT 0,
  humidity REAL NOT NULL DEFAULT 65.0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS transmissions (
  id SERIAL PRIMARY KEY,
  message TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'info',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
