name: "🔑 Attest"

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      image:
        description: "Image to attest"
        required: true
        type: string
      digest:
        description: "Digest of the image"
        required: true
        type: string

  workflow_dispatch:
    inputs:
      image:
        description: "Image to attest"
        required: true
        type: string
      digest:
        description: "Digest of the image"
        required: true
        type: string

jobs:
  attest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          project_id: trusted-builds
          workload_identity_provider: projects/629296473058/locations/global/workloadIdentityPools/homelab/providers/github

      - name: Attest
        uses: jonpulsifer/attester-action@main
        with:
          projectId: trusted-builds
          attestorId: provenance
          imageName: ${{ inputs.image }}
          imageDigest: ${{ inputs.digest }}
          keyProject: trusted-builds
          keyLocation: northamerica-northeast1
          keyRing: keys
          keyName: signer
          keyVersion: 1