name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_ID }}
    services:
      postgres:
        image: postgres:16@sha256:bb4e68544120c654e8b4f7ffd731be76b8d30ed7ac3a53f454290f02cf253b7c
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wishlist
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build --filter='!authme'
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/db?schema=public
          DIRECT_URL: postgresql://postgres:postgres@localhost:5432/db?schema=public

      - name: Test
        run: pnpm test

  containerize:
    name: containerize
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: request-headers
            stack: nextjs
          - app: nested
            stack: nestjs
          - app: rosie
            stack: generic
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker Meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5
        id: meta
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
          flavor: |
            latest=true

      - name: Build and push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          build-args: |
            APP=${{ matrix.app }}
            TURBO_TEAM=${{ secrets.VERCEL_ID }}
            TURBO_TOKEN=${{ secrets.VERCEL_TOKEN }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ${{ matrix.stack == 'nextjs' && 'nextjs.Dockerfile' || 'Dockerfile' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: true
          provenance: true

  deploy:
    strategy:
      matrix:
        app: [request-headers, rosie, nested]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [build, containerize]
    runs-on: ts
    environment:
      name: ${{ matrix.app }}
      url: https://${{matrix.app}}.lolwtf.ca
    env:
      ARGOCD_URL: argo-argocd-server.argo
    steps:
      - name: Download ArgoCD CLI
        run: |
          curl -sSL -o /tmp/argocd http://${{ env.ARGOCD_URL }}/download/argocd-linux-amd64
          chmod +x /tmp/argocd
          sudo mv /tmp/argocd /usr/local/bin/argocd
      - name: Login to ArgoCD
        run: |
          echo y | argocd login --insecure --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web ${{ env.ARGOCD_URL }}
      - name: Update application revision and image to ${{ github.sha }}
        run: |
          argocd app set ${{ matrix.app }} --revision=${{ github.sha }} --kustomize-image=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app }}:${{ github.sha }}
      - name: Sync and wait for application to be healthy
        run: |
          argocd app sync ${{ matrix.app }} --prune
          argocd app wait ${{ matrix.app }} --timeout 600
