name: "🐙 Build and Deploy with ArgoCD"

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App to deploy"
        required: true
        type: choice
        options:
          - slingshot
          - hub
          - truffle

jobs:
  containerize:
    name: "🐳 Containerize"
    uses: ./.github/workflows/containerize.yaml
    with:
      app: ${{ inputs.app }}
  
  # attest:
  #   needs: [containerize]
  #   name: "🔑 Attest"
  #   uses: ./.github/workflows/attest.yaml
  #   if: ${{ github.ref == 'refs/heads/main' }}
  #   with:
  #     image: ${{ needs.containerize.outputs.image }}
  #     digest: ${{ needs.containerize.outputs.digest }}

  deploy:
    needs: [containerize]
    name: "🐙 Deploy"
    runs-on: argocd-ts
    environment:
      name: ${{ inputs.app }}
      url: https://${{inputs.app}}.lolwtf.ca
    env:
      ARGOCD_URL: argo-argocd-server.argo
    steps:
      - name: Download ArgoCD CLI
        run: |
          curl -sSL -o /tmp/argocd http://${{ env.ARGOCD_URL }}/download/argocd-linux-amd64
          chmod +x /tmp/argocd
          sudo mv /tmp/argocd /usr/local/bin/argocd
      - name: Login to ArgoCD
        run: |
          echo y | argocd login --insecure --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web ${{ env.ARGOCD_URL }}
      - name: Point Argo CD at ${{ github.sha }} and image
        run: |
          APP="${{ inputs.app }}"
          SHA="${{ github.sha }}"
          OWNER="${{ github.repository_owner }}"
          IMAGE="ghcr.io/${OWNER}/${APP}:${SHA}"
          BASE_IMAGE_NAME="ghcr.io/${OWNER}/${APP}"

          argocd app set "$APP" \
            --revision="$SHA" \
            --kustomize-image "${BASE_IMAGE_NAME}=${IMAGE}"
